version: "3.8"

services:
  mongo-db:
    image: mongo:7.0.7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: sporte*1815
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
